version: '3.8'

services:

#---------------------------------database-services-----------------------------------
  mongodb:

    container_name: mongodb_services

    image: mongo:latest

    environment:

       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}

       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

    volumes:

      - mongo_data:/data/db

    expose:

      - "27017"

    restart: unless-stopped

    healthcheck:

      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]

      interval: 30s

      timeout: 10s

      retries: 5

    networks:

      - imagift_network

#----------------------------------backend-services------------------------------------
  server:

    build:

      context: ./server

      dockerfile: Dockerfile

    env_file:

      - ./server/.env

    expose:

      - "4000"

    depends_on:

      mongodb:

        condition: service_healthy

    restart: unless-stopped

    networks:

      - imagift_network

#-------------------------------------frontend-services--------------------------------

  client:

    container_name: client

    build:

      context: ./client

      dockerfile:  Dockerfile

      args:

       - VITE_BACKEND_URL=

    expose:

      - "80"

    networks:

      - imagift_network

#-------------------------------------nginx------------------------------------

  nginx:

    container_name: nginx

    image: nginx:1.25.3-alpine

    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:

      - "80:80"

    depends_on:

       server:

         condition: service_started

       client:

         condition: service_started

    restart: unless-stopped

    networks:

      - imagift_network

#---------------------------networks---------------------------

networks:

  imagift_network:

    driver: bridge
#-----------------------------volumes------------------

volumes:

  mongo_data:
